name: Generate UsersPrefs JSON manifest

on:
  push:
    paths:
      - userPrefs.h
    branches:
      - master

jobs:
  generate-userprefs:
    runs-on: [ubuntu-latest, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clang
        run: sudo apt-get install -y clang

      - name: Install trunk
        run: curl https://get.trunk.io -fsSL | bash

      - name: Generate userPrefs.jsom
        run: python3 ./bin/build-userprefs-json.py

      - name: Trunk format json
        run: trunk format userPrefs.jsonc

      - name: Commit userPrefs.jsonc
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add userPrefs.jsonc
          git commit -m "Update userPrefs.jsonc"
          git push
