name: Trigger release workflows upon Publish

on:
  release:
    types: [published, released]

permissions:
  contents: write
  packages: write
  checks: write

jobs:
  build-docker:
    uses: ./.github/workflows/docker_manifest.yml
    with:
      release_channel: |-
        ${{ contains(github.event.release.name, 'Beta') && 'beta' || contains(github.event.release.name, 'Alpha') && 'alpha' }}
    secrets: inherit

  package-ppa:
    strategy:
      fail-fast: false
      matrix:
        series:
          - jammy # 22.04
          - noble # 24.04
          - plucky # 25.04
          # - questing # 25.10
    uses: ./.github/workflows/package_ppa.yml
    with:
      ppa_repo: |-
        ppa:mymesh/${{ contains(github.event.release.name, 'Beta') && 'beta' || contains(github.event.release.name, 'Alpha') && 'alpha' }}
      series: ${{ matrix.series }}
    secrets: inherit
